const test = require('node:test');
const assert = require('node:assert/strict');
const { spawn } = require('node:child_process');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const port = 5167;
const dataPath = path.join(os.tmpdir(), `civicroute-api-test-${process.pid}.json`);
let server; let cookie; let complaintId;
const base = `http://127.0.0.1:${port}/api`;
async function request(pathname, options = {}) { const response = await fetch(`${base}${pathname}`, { ...options, headers: { ...(options.headers || {}), ...(cookie ? { Cookie: cookie } : {}) } }); return { response, body: await response.json() }; }
test.before(async () => { server = spawn(process.execPath, ['server.js'], { cwd: path.join(__dirname, '..'), env: { ...process.env, PORT: String(port), CIVICROUTE_DATA_PATH: dataPath, OFFICIAL_USERNAME: 'admin@civicroute.gov.in', OFFICIAL_PASSWORD: 'test-only-password', OFFICIAL_SESSION_SECRET: 'test-only-session-secret-with-enough-length', SMTP_HOST: '', SMTP_PORT: '', SMTP_USER: '', SMTP_PASS: '', SMTP_FROM: '' } }); await new Promise((resolve, reject) => { const timer = setTimeout(() => reject(new Error('Test server did not start')), 8000); server.stdout.on('data', (chunk) => { if (chunk.toString().includes('running on port')) { clearTimeout(timer); resolve(); } }); server.on('error', reject); }); });
test.after(() => { server?.kill(); if (fs.existsSync(dataPath)) fs.unlinkSync(dataPath); });
test('citizen registration persists despite unconfigured SMTP and public tracking works', async () => { const form = new FormData(); Object.entries({ fullName: 'Test Citizen', email: 'citizen@example.test', phone: '9876543210', address: 'Test Nagar', aadhaar: '123456789012', description: 'Large pothole near the school crossing', subject: 'Pothole near school' }).forEach(([key, value]) => form.append(key, value)); const { response, body } = await request('/complaints', { method: 'POST', body: form }); assert.equal(response.status, 201); assert.equal(body.email.attempted, false); assert.equal(body.email.delivered, false); complaintId = body.complaintId; const tracked = await request(`/complaints/${complaintId}`); assert.equal(tracked.response.status, 200); assert.equal(tracked.body.status, 'Routed'); assert.equal(tracked.body.citizen, undefined); assert.equal(tracked.body.aadhaar_hash, undefined); });
test('official routes reject unauthenticated and incorrect credentials', async () => { let result = await request('/official/complaints'); assert.equal(result.response.status, 401); result = await request('/official/login', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ username: 'admin@civicroute.gov.in', password: 'wrong' }) }); assert.equal(result.response.status, 401); });
test('official login, retrieval, lifecycle validation, statistics, and logout work', async () => { let result = await request('/official/login', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ username: 'admin@civicroute.gov.in', password: 'test-only-password' }) }); assert.equal(result.response.status, 200); cookie = result.response.headers.get('set-cookie').split(';')[0]; result = await request('/official/complaints'); assert.equal(result.response.status, 200); assert.equal(result.body.complaints.length, 1); assert.equal(result.body.complaints[0].citizen.email, 'citizen@example.test'); result = await request(`/official/complaints/${complaintId}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ status: 'Resolved', internalNote: 'Inspection queued.' }) }); assert.equal(result.response.status, 400); result = await request(`/official/complaints/${complaintId}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ status: 'In Progress', internalNote: 'Inspection queued.' }) }); assert.equal(result.response.status, 200); assert.equal(result.body.status, 'In Progress'); assert.equal(result.body.internalNote, 'Inspection queued.'); result = await request('/complaints/stats'); assert.equal(result.response.status, 200); assert.equal(result.body.inProgressCount, 1); result = await request('/official/logout', { method: 'POST' }); assert.equal(result.response.status, 200); cookie = null; result = await request('/official/session'); assert.equal(result.response.status, 401); });
