import './PortalInfo.css';

const CONTENT = {
  departments: { eyebrow: 'Departments', title: 'Departments and service areas', intro: 'CivicRoute routes reports to the appropriate municipal service area. The final routing can be reviewed before registration.', items: ['Roads & PWD', 'Water Supply', 'Electricity', 'Sanitation & Garbage', 'Public Health', 'Street Lighting', 'Environment & Pollution', 'Building & Encroachment', 'Public Transport', 'Parks & Recreation', 'Fire & Disaster Response'] },
  process: { eyebrow: 'Grievance process', title: 'From submission to resolution', intro: 'Your submission moves through a transparent lifecycle.', items: ['Submit your citizen and complaint details.', 'Review the AI-suggested department, category, and priority.', 'Receive a CivicRoute reference number after registration.', 'Track progress through Submitted, Routed, In Progress, and Resolved.'] },
  help: { eyebrow: 'Help / FAQ', title: 'Frequently asked questions', intro: 'Answers about the Step 1 citizen grievance service.', items: ['Can I write in Hindi or Marathi? Yes — CivicRoute supports English, Hindi, Marathi, Hinglish, and mixed-language descriptions.', 'Why is Aadhaar requested? This project validates a 12-digit identity value; it stores only a safe representation, never the full number.', 'Can I change routing details? Yes. The suggested department, category, and priority are editable before final registration.', 'How do I track a complaint? Enter your CivicRoute reference number on the Track Complaint page.'] },
  contact: { eyebrow: 'Contact us', title: 'Contact information', intro: 'CivicRoute is a project portal. No email delivery or official-login workflow is implemented in this step.', items: ['For a registered grievance, use your reference number on Track Complaint.', 'For immediate emergencies, contact the appropriate local emergency service.', 'Municipal official contact and email notifications are planned for later steps.'] },
  login: { eyebrow: 'Official login', title: 'Official access is coming soon', intro: 'This navigation item is a placeholder for the municipality official workflow planned in a later project step.', items: ['Citizen complaint registration and tracking do not require a login.', 'No official authentication or municipality actions are available yet.'] },
};
export default function PortalInfo({ page, navigate }) { const content = CONTENT[page]; return <main className="container info-page"><span className="eyebrow">{content.eyebrow}</span><h2>{content.title}</h2><p className="info-page__intro">{content.intro}</p><section>{content.items.map((item, index) => <article key={item}><b>{index + 1}</b><p>{item}</p></article>)}</section>{page === 'departments' || page === 'process' ? <button className="btn btn--primary" onClick={() => navigate('lodge')}>Lodge a complaint</button> : null}</main>; }
